services:
  mysql:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - mysql_data:/var/lib/mysql
  
  redis:
    image: redis:latest
    container_name: redis_cache
    restart: always
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
      - redis_data:/data

volumes:
 mysql_data:
 redis_data: